---
- name: web application deploy
  hosts: west
  remote_user: beast
  vars:
    branch: prod
    homedir: "/home/{{ user }}"
    org: aliencyborg
    repo: tilltax-2
    user: hank
    workdir: "{{ homedir }}/code/src/github.com/{{ org }}/{{ repo }}"

  tasks:
    - name: ensure workdir parent dir is present
      file:
        path: "{{ homedir }}/code/src/github.com/{{ org }}"
        state: directory

    - name: clone or update repo
      git:
        dest: "{{ workdir }}"
        repo: "https://github.com/{{ org }}/{{ repo }}.git"
        update: yes
        version: "{{ branch }}"

    - name: build docker image
      docker_image:
        force_source: yes
        name: tilltax-web
        source: build
        build:
          path: "{{ workdir }}"
          pull: no

    - name: run docker container
      docker_container:
        expose: 80
        image: tilltax-web
        name: tilltax-web
        recreate: yes
        restart_policy: always
        env:
          HSTS: "off"
          LETSENCRYPT_HOST: "www.tilltax.com,tilltax.com"
          PORT: "80"
          VIRTUAL_HOST: "www.tilltax.com,tilltax.com"

